default:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: postgres
      port: 5432
      user: airflow
      pass: airflow
      dbname: airflow
      schema: public  # You can define a different schema if needed
  target: dev
